name: Format Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"

      - name: Set up Python
        run: uv python install

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Switch to python directory
        working-directory: python
        run: echo "Switched to python directory"

      - name: Install Python dependencies
        run: make install-dev

      - name: Format with ruff
        run:  uv run ruff format --check

      - name: Switch to root directory
        working-directory: ..
        run: echo "Switched to root directory"

      - name: Format database package
        working-directory: database
        run: yarn && yarn run prettier . --check

      - name: Format frontend package
        working-directory: frontend
        run: yarn && yarn run prettier . --check

      - name: Format proxy package
        working-directory: proxy
        run: yarn && yarn run prettier . --check
