name: Format Frontend Pull Request

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  format-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Format frontend package
        working-directory: frontend
        run: yarn && yarn run prettier . --check