name: Lint Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"

      - name: Set up Python
        run: uv python install

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: make -C python install-dev

      - name: Lint with ruff
        run: uv run ruff check --output-format=github .

      - name: Lint imports with ruff
        run: uv run ruff check --select I --output-format=github .

      - name: Lint database package
        working-directory: database
        run: yarn && yarn run lint

      - name: Lint frontend package
        working-directory: frontend
        run: yarn && yarn run lint

      - name: Lint proxy package
        working-directory: proxy
        run: yarn && yarn run lint
