name: Lint Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-python:
    if: contains(github.event.pull_request.changed_files, 'python/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        working-directory: python
        run: make install-dev

      - name: Lint with ruff
        working-directory: python
        run: uv run ruff check --output-format=github .

      - name: Lint imports with ruff
        working-directory: python
        run: uv run ruff check --select I --output-format=github .

  lint-database:
    if: contains(github.event.pull_request.changed_files, 'database/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint database package
        working-directory: database
        run: yarn && yarn run lint

  lint-frontend:
    if: contains(github.event.pull_request.changed_files, 'frontend/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint frontend package
        working-directory: frontend
        run: yarn && yarn run lint

  lint-proxy:
    if: contains(github.event.pull_request.changed_files, 'proxy/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint proxy package
        working-directory: proxy
        run: yarn && yarn run lint
