name: Lint Python Pull Request

on:
  pull_request:
    branches: [main]
    paths:
      - 'python/**'
  workflow_dispatch:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.5.13'

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        working-directory: python
        run: make install-dev

      - name: Lint with ruff
        working-directory: python
        run: uv run ruff check --output-format=github .

      - name: Lint imports with ruff
        working-directory: python
        run: uv run ruff check --select I --output-format=github .
